config/routes.rb
Rails.application.routes.draw do
  resources :evaluations

  resources :establishments

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  belongs_to :establishment
  
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base

  has_many :evaluations
  has_many :contacts
  
  validates_presence_of :name
  
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  
  belongs_to :establishment

  validates_presence_of :establishment_id
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :set_establishment, only: [:show, :edit, :update, :destroy]

  # GET /establishments
  # GET /establishments.json
  def index
    @establishments = Establishment.all
  end

  # GET /establishments/1
  # GET /establishments/1.json
  def show
  end

  # GET /establishments/new
  def new
    @establishment = Establishment.new
  end

  # GET /establishments/1/edit
  def edit
  end

  # POST /establishments
  # POST /establishments.json
  def create
    @establishment = Establishment.new(establishment_params)

    respond_to do |format|
      if @establishment.save
        format.html { redirect_to @establishment, notice: 'Establishment was successfully created.' }
        format.json { render :show, status: :created, location: @establishment }
      else
        format.html { render :new }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establishments/1
  # PATCH/PUT /establishments/1.json
  def update
    respond_to do |format|
      if @establishment.update(establishment_params)
        format.html { redirect_to @establishment, notice: 'Establishment was successfully updated.' }
        format.json { render :show, status: :ok, location: @establishment }
      else
        format.html { render :edit }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establishments/1
  # DELETE /establishments/1.json
  def destroy
    @establishment.destroy
    respond_to do |format|
      format.html { redirect_to establishments_url, notice: 'Establishment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establishment
      @establishment = Establishment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def establishment_params
      params.require(:establishment).permit(:name, :description, :address)
    end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
    @establishments = Establishment.all
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)
    
    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:pointing, :good_points, :bad_points, :would_back, :establishment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/establishments/_form.html.erb
<%= form_for(@establishment) do |f| %>
  <% if @establishment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@establishment.errors.count, "error") %> prohibited this establishment from being saved:</h2>

      <ul>
      <% @establishment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/establishments/edit.html.erb
<h1>Editing Establishment</h1>

<%= render 'form' %>

<%= link_to 'Show', @establishment %> |
<%= link_to 'Back', establishments_path %>

app/views/establishments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Establishments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @establishments.each do |establishment| %>
      <tr>
        <td><%= establishment.name %></td>
        <td><%= establishment.description %></td>
        <td><%= establishment.address %></td>
        <td><%= link_to 'Show', establishment %></td>
        <td><%= link_to 'Edit', edit_establishment_path(establishment) %></td>
        <td><%= link_to 'Destroy', establishment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Establishment', new_establishment_path %>

app/views/establishments/new.html.erb
<h1>New Establishment</h1>

<%= render 'form' %>

<%= link_to 'Back', establishments_path %>

app/views/establishments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @establishment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @establishment.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @establishment.address %>
</p>

<%= link_to 'Edit', edit_establishment_path(@establishment) %> |
<%= link_to 'Back', establishments_path %>

app/views/evaluations/_form.html.erb
<%= form_for(@evaluation) do |f| %>
  <% if @evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% @evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :establishment_id %><br>
    <%= f.collection_select(:establishment_id, @establishments, :id, :name) %>
  </div>
  
  <div class="field">
    <%= f.label :pointing %><br>
    <%= f.number_field :pointing %>
  </div>
  <div class="field">
    <%= f.label :good_points %><br>
    <%= f.text_area :good_points %>
  </div>
  <div class="field">
    <%= f.label :bad_points %><br>
    <%= f.text_area :bad_points %>
  </div>
  <div class="field">
    <%= f.label :would_back %><br>
    <%= f.check_box :would_back %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evaluations</h1>

<table>
  <thead>
    <tr>
      <th>Pointing</th>
      <th>Good points</th>
      <th>Bad points</th>
      <th>Would back</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.pointing %></td>
        <td><%= evaluation.good_points %></td>
        <td><%= evaluation.bad_points %></td>
        <td><%= evaluation.would_back %></td>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pointing:</strong>
  <%= @evaluation.pointing %>
</p>

<p>
  <strong>Good points:</strong>
  <%= @evaluation.good_points %>
</p>

<p>
  <strong>Bad points:</strong>
  <%= @evaluation.bad_points %>
</p>

<p>
  <strong>Would back:</strong>
  <%= @evaluation.would_back %>
</p>

<%= link_to 'Edit', edit_evaluation_path(@evaluation) %> |
<%= link_to 'Back', evaluations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avaliaorango</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>